name: shared
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    name: Code quality checks
    runs-on: ubuntu-latest-8-cores
    concurrency:
      group: ci-${{ github.head_ref }}-shared
      cancel-in-progress: true
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "npm"
          cache-dependency-path: |
            package-lock.json
            */package-lock.json
      - run: npm
      - name: Run ESLint
        run: npm run eslint:check
      - name: Prettier
        run: npm run prettier:check
