name: Lint
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    name: Code quality checks
    runs-on: ubuntu-latest
    concurrency:
      group: ci-${{ github.head_ref }}
      cancel-in-progress: true
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm i
      - name: Run ESLint
        run: npm run eslint:check
      - name: Prettier
        run: npm run prettier:check
